package org.lineageos.xiaomi_tws

import java.util.UUID

object EarbudsConstants {

    private val UUID_XIAOMI_FAST_CONNECT = UUID.fromString("0000FD2D-0000-1000-8000-00805f9b34fb")
    private val UUID_XIAOMI_XIAOAI = UUID.fromString("00001101-0000-1000-8000-008584d01810")
    private val UUID_SPP = UUID.fromString("00001101-0000-1000-8000-00805f9b34fb")

    val XIAOMI_SPP_UUIDS = arrayOf(UUID_XIAOMI_FAST_CONNECT, UUID_XIAOMI_XIAOAI, UUID_SPP)

    const val XIAOMI_MMA_DATA_LENGTH = 22


    const val XIAOMI_MMA_RESPONSE_STATUS_OK: Byte = 0x00

    const val XIAOMI_MMA_OPCODE_GET_DEVICE_INFO: Byte = 0x02
    const val XIAOMI_MMA_OPCODE_SET_DEVICE_CONFIG: Byte = 0xF2.toByte()
    const val XIAOMI_MMA_OPCODE_GET_DEVICE_CONFIG: Byte = 0xF3.toByte()
    const val XIAOMI_MMA_OPCODE_NOTIFY_DEVICE_INFO: Byte = 0x0E.toByte()
    const val XIAOMI_MMA_OPCODE_NOTIFY_DEVICE_CONFIG: Byte = 0xF4.toByte()

    const val XIAOMI_MMA_MASK_GET_VERSION = 1
    const val XIAOMI_MMA_MASK_GET_VID_PID = 3
    const val XIAOMI_MMA_MASK_GET_UBOOT_VERSION = 6
    const val XIAOMI_MMA_MASK_GET_BATTERY = 7

    const val XIAOMI_MMA_NOTIFY_TYPE_BATTERY: Byte = 0x00
    const val XIAOMI_MMA_NOTIFY_TYPE_NCM: Byte = 0x04

    const val XIAOMI_MMA_CONFIG_BUTTON_MODE = 0x0002
    const val XIAOMI_MMA_CONFIG_MULTI_CONNECT = 0x0004
    const val XIAOMI_MMA_CONFIG_EQUALIZER_MODE = 0x0007
    const val XIAOMI_MMA_CONFIG_FIND_EARBUDS = 0x0009
    const val XIAOMI_MMA_CONFIG_NOISE_CANCELLATION_LIST = 0x000A
    const val XIAOMI_MMA_CONFIG_NOISE_CANCELLATION_MODE = 0x000B
    const val XIAOMI_MMA_CONFIG_EARBUDS_IN_EAR_MODE = 0x000C
    const val XIAOMI_MMA_CONFIG_SN = 0x0027

    const val XIAOMI_MMA_CONFIG_BUTTON_FUNCTION_DISABLED: Byte = 0x08
    const val XIAOMI_MMA_CONFIG_BUTTON_FUNCTION_VOICE_ASSISTANT: Byte = 0x00
    const val XIAOMI_MMA_CONFIG_BUTTON_FUNCTION_PLAY_PAUSE: Byte = 0x01
    const val XIAOMI_MMA_CONFIG_BUTTON_FUNCTION_PREVIOUS_TRACK: Byte = 0x02
    const val XIAOMI_MMA_CONFIG_BUTTON_FUNCTION_NEXT_TRACK: Byte = 0x03
    const val XIAOMI_MMA_CONFIG_BUTTON_FUNCTION_VOLUME_UP: Byte = 0x04
    const val XIAOMI_MMA_CONFIG_BUTTON_FUNCTION_VOLUME_DOWN: Byte = 0x05
    const val XIAOMI_MMA_CONFIG_BUTTON_FUNCTION_NOISE_CONTROL: Byte = 0x06
    const val XIAOMI_MMA_CONFIG_BUTTON_FUNCTION_SCREENSHOT: Byte = 0x09

    const val XIAOMI_MMA_CONFIG_EQUALIZER_MODE_DEFAULT: Byte = 0x00
    const val XIAOMI_MMA_CONFIG_EQUALIZER_MODE_VOCAL_ENHANCE: Byte = 0x01
    const val XIAOMI_MMA_CONFIG_EQUALIZER_MODE_BASS_BOOST: Byte = 0x05
    const val XIAOMI_MMA_CONFIG_EQUALIZER_MODE_TREBLE_BOOST: Byte = 0x06
    const val XIAOMI_MMA_CONFIG_EQUALIZER_MODE_VOLUME_BOOST: Byte = 0x07
    const val XIAOMI_MMA_CONFIG_EQUALIZER_MODE_HARMAN: Byte = 0x14
    const val XIAOMI_MMA_CONFIG_EQUALIZER_MODE_HARMAN_MASTER: Byte = 0x15

    const val XIAOMI_MMA_CONFIG_NOISE_CANCELLATION_MODE_OFF: Byte = 0x00
    const val XIAOMI_MMA_CONFIG_NOISE_CANCELLATION_MODE_ON: Byte = 0x01
    const val XIAOMI_MMA_CONFIG_NOISE_CANCELLATION_MODE_TRANSPARENCY: Byte = 0x02
}
